{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {
    "collapsed": false
   },
   "source": [
    "# Q&A（太长不看版本）\n",
    "\n",
    "<font size=3> **Q:** 出现 `RuntimeError: cublas64_100.dll not found` </font>\n",
    "\n",
    "<font size=3> **A:** 可能是与cuda没有安装，也有可能是没有设置环境变量(这里推荐安装完cuda重启一下)</font>\n",
    "<font size=3>      可以参考：[https://blog.csdn.net/HaoZiHuang/article/details/107891428](https://blog.csdn.net/HaoZiHuang/article/details/107891428)\n",
    "\n",
    "-----------\n",
    "\n",
    "<font size=3> **Q:** 出现 `ImportError: Could not find 'cudnn64_7.dll'`</font>\n",
    "\n",
    "<font size=3> **A:** 可能是与cuda对应的cudnn没有安装</font>\n",
    "\n",
    "-----------\n",
    "\n",
    "<font size=3> **Q:** 我明明安装了cudnn, 却仍然出现 `ImportError: Could not find 'cudnn64_7.dll'`</font>\n",
    "\n",
    "<font size=3> **A:** 重启一下电脑就好了，因为windows环境变量的设置一般都需要重启</font>\n",
    "\n",
    "----------\n",
    "\n",
    "<font size=3> **Q:** CUDA和CUDnn下载贼慢怎么办？</font>\n",
    "\n",
    "<font size=3> **A:** 可以copy其链接，扔到某雷里边下载，实测5M/s，相当快 </font>\n",
    "\n",
    "<font size=2> 这里有CUDA10网盘链接，感谢super松同学：链接: https://pan.baidu.com/s/1V2vTYMa1Il5R4GXrTNM3HQ 提取码: cyjx </font>\n",
    "\n",
    "----------\n",
    "\n",
    "<font size=3> **Q:** CUDA的组件都要安装吗？</font>\n",
    "\n",
    "<font size=3> **A:** 不需要哦，可以往下翻网页，我们只需要安装一下部分 </font>\n",
    "\n",
    "----------\n",
    "\n",
    "<font size=3> **Q:** 出现了 `ExternalError:  Cuda error(38), no CUDA-capable device is detected.`</font>\n",
    "\n",
    "<font size=3> **A:** 是显卡驱动安装出了问题，可以查看本网页的第5部分安装对应的显卡驱动 </font>\n",
    "\n",
    "----------\n",
    "\n",
    "<font size=3> **Q:** 出现了 `Cuda error(35), CUDA driver version is insufficient for CUDA runtime version`</font>\n",
    "\n",
    "<font size=3> **A:** 是显卡需要更新，可以查看本网页的第5部分安装对应的显卡驱动 </font>\n",
    "\n",
    "----------\n",
    "\n",
    "\n",
    "欢迎大家留言提问或者补充"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "collapsed": false
   },
   "source": [
    "## 0.写在前面\n",
    "目前 `paddlepaddle` 支持`Python`版本为：\n",
    "- Python 2 版本是 2.7.15+\n",
    "- Python 3 版本是 3.5.1+/3.6/3.7\n",
    "\n",
    "<font face=宋体 color=red>**也就是说，当前时间，暂时不支持Python3.8**</font>\n",
    "\n",
    "- pip/pip3 版本要求是 9.0.1+\n",
    "- Python 和 pip 均是 64 位\n",
    "\n",
    "<font face=宋体 color=red>**也就是说，当前时间，暂时不支持32位的系统**</font>\n",
    "\n",
    "<font face=宋体 color=red>**另外，需要有英伟达家的显卡........**</font>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "collapsed": false
   },
   "source": [
    "## 1.新建环境\r\n",
    "为了排除环境问题，咱们先新建一个环境：\r\n",
    "打开`anaconda Prompt` (不知道jie个si啥的安装一下anaconda)，输入\r\n",
    "\r\n",
    "```shell\r\n",
    "conda create -n paddle_gpu python=3.6\r\n",
    " ```\r\n",
    " `-n, --name` 参数指定环境名称\r\n",
    " `python=3.6` 的意思是指定Python版本为3.6\r\n",
    " \r\n",
    " ---------------\r\n",
    " 插一句，如果conda下载对应的包贼慢的话，可以换一下源，这里实例为换清华源：\r\n",
    "```shell\r\n",
    "(base) C:\\Users\\user> conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/\r\n",
    "(base) C:\\Users\\user> conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge\r\n",
    "(base) C:\\Users\\user> conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/\r\n",
    "\r\n",
    "# 设置搜索时显示通道地址\r\n",
    "(base) C:\\Users\\user> conda config --set show_channel_urls yes\r\n",
    "```\r\n",
    " 大家也可以根据情况更换百度源，阿里云源等\r\n",
    " \r\n",
    " ---------------\r\n",
    "新环境准备完毕后，激活就可以：\r\n",
    "```shell\r\n",
    "(base) C:\\Users\\user>conda activate paddle_gpu\r\n",
    " \r\n",
    "(paddle_gpu) C:\\Users\\user>\r\n",
    " ```"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "collapsed": false
   },
   "source": [
    " ## 2.cuda安装\n",
    " \n",
    "<font size=4>在进行下一步之前，我们需要安装**cuda**和**cudnn**</font>\n",
    " \n",
    "<font size=4>CUDA（Compute Unified Device Architecture），是显卡厂商NVIDIA推出的**运算平台**。 \n",
    "CUDA™是一种由NVIDIA推出的通用并行计算架构，该架构使GPU能够解决复杂的计算问题。</font>\n",
    "\n",
    "<font size=4>点击jie个下载链接：</font>[https://developer.nvidia.com/cuda-downloads](https://developer.nvidia.com/cuda-downloads)\n",
    "\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807190248940.png)\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807190131922.png)\n",
    "\n",
    "<font size=4>**(应该没有不是win10系统的老铁吧？不会吧不会吧？)**</font>\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807190413896.png)\n",
    "\n",
    "<font size=4>可以右键，复制链接，然后用某雷下载，可以看到速度还kuo以</font>\n",
    "\n",
    "<font size=4>就是这个链接：</font>\n",
    "\n",
    "https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.0.130_411.31_win10\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807184032845.png)\n",
    "\n",
    "<font size=4>选择一个cuda的**临时**解压路径</font>\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807185105878.png)\n",
    "\n",
    "<font size=4>等待解压结束 (我这三年前买的电脑，还挺慢的......)</font>\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807185131848.png)\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807191452971.png)\n",
    "\n",
    "<font size=4>再等一会儿......</font>\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807191537354.png)\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807191722745.png)\n",
    "\n",
    "<font size=4>推荐选择自定义，如果想选择全家桶也可以(多半用不到)</font>\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807191849296.png)\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807192137787.png)\n",
    "\n",
    "<font size=4>这个 visual studio integration 也可以不选：</font>\n",
    "(此图片摘自博客：[https://blog.csdn.net/XunCiy/article/details/89070315](https://blog.csdn.net/XunCiy/article/details/89070315))\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/2019040715270168.png)\n",
    "\n",
    "<font size=4>推荐换个地方安装：</font>\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807193540253.png)\n",
    "\n",
    "<font size=4>电风扇又要吹一会儿了.......(安装过程中可能屏幕有闪烁，不要慌问题不大)</font>\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807194144806.png)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "collapsed": false
   },
   "source": [
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/202008071949585.png)\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807195012870.png)\n",
    "\n",
    "<font size=4>安装完毕后，测试一下吧，`win+R` 输入cmd，在cmd中输入 `nvcc -V`</font>\n",
    "<font size=4>OKOK，安装成功：</font>\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/2020080720374754.png)\n",
    "\n",
    "<font size=4>也可以从环境变量中检查：</font>\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807204335564.png)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "collapsed": false
   },
   "source": [
    "## 3.CUDNN的安装\n",
    "\n",
    "<font size=4>NVIDIA cuDNN是用于深度神经网络的**GPU加速库**。它强调性能、易用性和低内存开销。NVIDIA cuDNN可以集成到更高级别的机器学习框架中，如谷歌的Tensorflow、加州大学伯克利分校的流行caffe软件。简单的插入式设计可以让开发人员专注于设计和实现神经网络模型，而不是简单调整性能，同时还可以在GPU上实现高性能现代并行计算。</font>\n",
    "\n",
    "<font size=4>这是下载地址：</font>\n",
    "[https://developer.nvidia.com/rdp/cudnn-download](https://developer.nvidia.com/rdp/cudnn-download)\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807210051426.png)\n",
    "\n",
    "<font size=4>这里的话，得注册一下</font>\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807210144132.png)\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/2020080721065325.png)\n",
    "\n",
    "<font size=4>注册并填了一个问卷之后，点击同意：</font>\n",
    "  \n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807215309851.png)\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807215503531.png)\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807220013293.png)\n",
    "\n",
    "<font size=4>记住后边一定是 for CUDA10.0 或者 for CUDA9.0，别的可不行啊</font>\n",
    "<font size=4>和刚才一样，右键复制链接，扔到某雷中下载：</font>\n",
    "\n",
    "https://developer.nvidia.com/compute/machine-learning/cudnn/secure/7.6.5.32/Production/10.0_20191031/cudnn-10.0-windows10-x64-v7.6.5.32.zip\n",
    "\n",
    "\n",
    "<font size=4>下载完毕后，将其解压缩，里面有三个文件夹：</font>\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807220805643.png)\n",
    "\n",
    "<font size=4>将这三个文件夹的内容分别放到之前CUDA的文件夹对应的目录中：</font>\n",
    "\n",
    "<font size=4>(就是将解压后得到的的bin ，include 和lib文件夹分别复制到cuda安装路径下与cuda的bin ，include 和lib文件夹合并)</font>\n",
    "  \n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807221038827.png)\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807221204370.png)\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200807221436418.png)\n",
    "\n",
    "<font size=4>到此为止，需要重启一下电脑，因为环境变量的设置，在window下大多要重启</font>\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "collapsed": false
   },
   "source": [
    "## 4.Paddlepaddle_GPU安装\n",
    "\n",
    "<font size=4>铺垫了这么多，终于走到这一步了：</font>\n",
    "<font size=4>打开 `anaconda prompt`:</font>\n",
    "```shell\n",
    "# 打开我们之前建立的环境\n",
    "> conda activate paddle_gpu\n",
    "> python -m pip install paddlepaddle-gpu==1.8.3.post107 -i https://mirror.baidu.com/pypi/simple\n",
    "```\n",
    "<font size=4>静静地等待它安装好就行了：</font>\n",
    "\n",
    "<font size=4>接下来在这个中断运行：</font>\n",
    "```shell\n",
    ">>> import paddle.fluid\n",
    ">>> paddle.fluid.install_check.run_check()\n",
    "```\n",
    "<font size=4>如果出现 `Your Paddle Fluid is installed successfully!`，说明您已成功安装。</font>\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/2020080722290485.png)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "collapsed": false
   },
   "source": [
    "## 5.安装对应的显卡驱动\n",
    "\n",
    "<font face=宋体 size=4>首先先查一下自己的显卡型号：</font>\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200809000706108.png)\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200809000831565.png)\n",
    "\n",
    "<font face=宋体 size=4>看到我的显卡是`GeForce GTX 1050`</font>\n",
    "\n",
    "\n",
    "<font face=宋体 size=4>在官方下载网站：[https://www.nvidia.cn/Download/index.aspx?lang=cn](https://www.nvidia.cn/Download/index.aspx?lang=cn)\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/2020080900114669.png)\n",
    "  \n",
    "<font face=宋体>找到对应的配置，注意笔记本电脑要注意选择(`notebook版本`)，点击搜索</font>\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/2020080900145587.png)\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200809001341365.png)\n",
    "  \n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200809001440460.png)\n",
    "\n",
    "<font face=宋体 size=4>下载完毕后打开程序</font>\n",
    "\n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200808212915628.png)\n",
    "  \n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200808213113639.png)\n",
    "  \n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200808213148754.png)\n",
    "  \n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200808213200212.png)\n",
    "  \n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/2020080821342057.png)\n",
    "  \n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200808213438221.png)\n",
    "  \n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/2020080821351095.png)\n",
    "  \n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200808213755261.png)\n",
    "  \n",
    "<font face=宋体 size=4>一路默认即可，最后验证一下：</font>\n",
    "\n",
    "<font face=宋体 size=4>win + R 输入 cmd：</font>\n",
    "  \n",
    "<font face=宋体 size=4>`nvidia-smi`</font>\n",
    "  \n",
    "![在这里插入图片描述](https://img-blog.csdnimg.cn/20200809001838890.png)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "PaddlePaddle 1.8.0 (Python 3.5)",
   "language": "python",
   "name": "py35-paddle1.2.0"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
